//! `sujay_ui` — native GPU-rendered DJ console UI.
//!
//! This crate is a pure Rust rlib (no NAPI, no Node.js dependency).
//! It is linked directly by the `sujay-app` binary.

pub mod ui_state;

#[cfg(any(target_os = "macos", target_os = "windows"))]
mod renderer_wgpu_shared;

#[cfg(target_os = "macos")]
#[path = "renderer.rs"]
pub(crate) mod renderer;

#[cfg(target_os = "windows")]
#[path = "renderer_windows.rs"]
pub(crate) mod renderer;

#[cfg(all(target_os = "macos", feature = "gpui-preview"))]
mod gpui_preview;

/// Re-export `UiAction` for consumers.
#[cfg(any(target_os = "macos", target_os = "windows"))]
pub use renderer::UiAction;

/// Attach a native GPU-rendered view to a raw NSView / HWND pointer.
///
/// On macOS pass the `ns_view` pointer from winit's `AppKitWindowHandle`.
pub fn attach_raw(nsview_ptr: *mut std::ffi::c_void, x: f64, y: f64, width: f64, height: f64) {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    unsafe { renderer::attach(nsview_ptr, x, y, width, height); }
}

/// Resize / reposition the native view within the parent window.
pub fn set_frame_raw(x: f64, y: f64, width: f64, height: f64) {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    unsafe { renderer::set_frame(x, y, width, height); }
}

/// Detach and destroy the native view.
pub fn detach_raw() {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    unsafe { renderer::detach(); }
}

/// Set decimated waveform samples for the specified deck (1 = A, 2 = B).
pub fn set_waveform_raw(deck: u32, samples: Vec<f32>) {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    {
        let deck_index = if deck <= 1 { 0 } else { 1 };
        renderer::set_waveform(deck_index, samples);
    }
}

/// Update playback position for a deck.
pub fn set_deck_progress_raw(deck: u32, position_frames: f32, total_frames: f32, sample_rate: f32) {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    {
        let deck_index = if deck <= 1 { 0 } else { 1 };
        renderer::set_deck_progress(deck_index, position_frames, total_frames, sample_rate);
    }
}

/// Update beat / intro / outro markers for a deck.
pub fn set_deck_markers_raw(deck: u32, beats: Vec<f32>, intro: Option<f32>, outro: Option<f32>) {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    {
        let deck_index = if deck <= 1 { 0 } else { 1 };
        renderer::set_deck_markers(deck_index, beats, intro, outro);
    }
}

/// Push a new console state snapshot (deck labels, BPM, crossfader, …).
pub fn set_console_state_raw(state: ui_state::ConsoleVisualState) {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    renderer::set_console_state(state);
}

/// Push a mouse event from the host windowing system into the UI renderer.
///
/// `kind`: 0 = cursor moved, 1 = left-button pressed, 2 = left-button released.
/// `x`, `y`: logical points, top-left origin, relative to the view's top-left corner.
pub fn push_mouse_event_raw(kind: u8, x: f32, y: f32) {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    renderer::push_mouse_event(kind, x, y);
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    let _ = (kind, x, y);
}

/// Drain and return all pending [`UiAction`]s generated by user interaction.
#[cfg(any(target_os = "macos", target_os = "windows"))]
pub fn poll_actions_raw() -> Vec<UiAction> {
    renderer::drain_actions()
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
pub fn poll_actions_raw() -> Vec<std::convert::Infallible> {
    vec![]
}

/// Return a snapshot of the beat grid (audio frame indices) and current
/// position for a deck (1 = A, 2 = B).  Returns `None` when the platform
/// does not support a native UI.
pub fn get_deck_beat_info_raw(deck: u32) -> Option<(Vec<f32>, f32)> {
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    {
        let deck_index = if deck <= 1 { 0 } else { 1 };
        let guard = renderer::DECK_VISUALS.lock().ok()?;
        let visual = &guard[deck_index];
        Some((visual.beats.clone(), visual.progress))
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    { let _ = deck; None }
}
