/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioInputStream {
  /**
   * Create a new audio input stream.
   * The callback receives Float32Array chunks of audio data.
   */
  constructor(deviceId: string | undefined | null, channels: number | undefined | null, sampleRate: number | undefined | null, callback: (data: Float32Array) => void)
  /** Stops input capture and releases the device handle. */
  close(): void
}

export declare class AudioOutputStream {
  constructor(deviceId?: string | undefined | null, channels?: number | undefined | null, sampleRate?: number | undefined | null)
  /** Write PCM frames (interleaved Float32) into the output queue. */
  write(chunk: Float32Array): void
  /** Returns the number of samples currently in the queue. */
  queueSize(): number
  /** Clears any queued audio data, useful when seeking. */
  clear(): void
  /** Stops playback and releases the device handle. */
  close(): void
}

/** Returns the crate version so JS can verify the native module loaded correctly. */
export declare function addonVersion(): string

export interface AudioDeviceInfo {
  id: string
  name: string
  maxInputChannels: number
  maxOutputChannels: number
  defaultSampleRate?: number
}

export declare function listAudioDevices(): Array<AudioDeviceInfo>
