/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioEngine {
  /** Create a new AudioEngine instance */
  constructor(deviceId: string | undefined | null, channels: number | undefined | null, sampleRate: number | undefined | null, stateCallback: (state: AudioEngineStateUpdate) => void)
  /**
   * Configure audio device and start output stream
   * Can be called multiple times to switch devices without losing engine state
   */
  configureDevice(config: DeviceConfig): void
  /** Load PCM data onto a deck */
  loadTrack(deck: number, pcmData: Float32Array, bpm?: number | undefined | null, trackId?: string | undefined | null): void
  /** Start playback on a deck */
  play(deck: number): void
  /** Stop playback on a deck */
  stop(deck: number): void
  /** Seek within a deck (position: 0.0 to 1.0) */
  seek(deck: number, position: number): void
  /** Set crossfader position (0.0 = full A, 1.0 = full B) */
  setCrossfaderPosition(position: number): void
  /** Start auto crossfade */
  startCrossfade(targetPosition: number | undefined | null, duration: number): void
  /** Set master tempo (BPM) */
  setMasterTempo(bpm: number): void
  /** Set deck gain (0.0 to 1.0) */
  setDeckGain(deck: number, gain: number): void
  /** Set cue enabled for a deck */
  setDeckCueEnabled(deck: number, enabled: boolean): void
  /**
   * Set channel configuration for main and cue outputs
   * channel values: -1 means disabled, 0+ means the output channel index
   */
  setChannelConfig(mainLeft: number, mainRight: number, cueLeft: number, cueRight: number): void
  /** Get current state */
  getState(): AudioEngineStateUpdate
  /** Clean up and stop the engine */
  close(): void
}

/** Returns the crate version so JS can verify the native module loaded correctly. */
export declare function addonVersion(): string

export interface AudioDeviceInfo {
  name: string
  maxInputChannels: number
  maxOutputChannels: number
  defaultSampleRate?: number
}

/** State update sent to JavaScript */
export interface AudioEngineStateUpdate {
  deckAPosition?: number
  deckBPosition?: number
  deckAPlaying: boolean
  deckBPlaying: boolean
  crossfaderPosition: number
  isCrossfading: boolean
  deckAPeak: number
  deckBPeak: number
  deckAPeakHold: number
  deckBPeakHold: number
  masterTempo: number
  deckATrackId?: string
  deckBTrackId?: string
  deckAGain: number
  deckBGain: number
  deckACueEnabled: boolean
  deckBCueEnabled: boolean
  /** Reason for this state update: "periodic", "seek", "play", "stop", "load", etc. */
  updateReason: string
}

/** Device configuration for configureDevice() */
export interface DeviceConfig {
  /** Device ID (device name, stable across restarts) */
  deviceId?: string
  /** Main output channels [left, right], -1 for disabled */
  mainChannels?: Array<number>
  /** Cue output channels [left, right], -1 for disabled */
  cueChannels?: Array<number>
}

export declare function listAudioDevices(): Array<AudioDeviceInfo>
