/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioEngine {
  /** Create a new AudioEngine instance */
  constructor(deviceId: string | undefined | null, channels: number | undefined | null, sampleRate: number | undefined | null, stateCallback: (state: AudioEngineStateUpdate) => void)
  /**
   * Configure audio device and start output stream
   * Can be called multiple times to switch devices without losing engine state
   */
  configureDevice(config: DeviceConfig): void
  /** Load PCM data onto a deck */
  loadTrack(deck: number, pcmData: Float32Array, bpm?: number | undefined | null, trackId?: string | undefined | null): void
  /** Start playback on a deck */
  play(deck: number): void
  /** Stop playback on a deck */
  stop(deck: number): void
  /** Seek within a deck (position: 0.0 to 1.0) */
  seek(deck: number, position: number): void
  /** Set crossfader position (0.0 = full A, 1.0 = full B) */
  setCrossfaderPosition(position: number): void
  /** Start auto crossfade */
  startCrossfade(targetPosition: number | undefined | null, duration: number): void
  /** Set master tempo (BPM) */
  setMasterTempo(bpm: number): void
  /** Set deck gain (0.0 to 1.0) */
  setDeckGain(deck: number, gain: number): void
  /**
   * Set EQ cut (kill switch) for a specific band on a deck
   * band: "low", "mid", "high"
   */
  setEqCut(deck: number, band: string, enabled: boolean): void
  /** Get EQ cut state for a deck */
  getEqCutState(deck: number): EqCutStateJs
  /** Set cue enabled for a deck */
  setDeckCueEnabled(deck: number, enabled: boolean): void
  /**
   * Set channel configuration for main and cue outputs
   * channel values: -1 means disabled, 0+ means the output channel index
   */
  setChannelConfig(mainLeft: number, mainRight: number, cueLeft: number, cueRight: number): void
  /** Get current state */
  getState(): AudioEngineStateUpdate
  /** Enable or disable microphone input */
  setMicEnabled(enabled: boolean): void
  /** Set microphone gain */
  setMicGain(gain: number): void
  /** Set talkover ducking level (0.0 to 1.0 - how much to reduce music) */
  setTalkoverDucking(ducking: number): void
  /** Set loop region for a deck (positions in 0.0-1.0 range) */
  setLoop(deck: number, start: number, end: number, enabled: boolean): void
  /**
   * Set beat loop for a deck using beat grid positions
   * start_seconds and end_seconds are calculated from beat grid on TypeScript side
   */
  setBeatLoop(deck: number, startSeconds: number, endSeconds: number): void
  /** Clear loop for a deck */
  clearLoop(deck: number): void
  /** Clean up and stop the engine */
  close(): void
}

/** Returns the crate version so JS can verify the native module loaded correctly. */
export declare function addonVersion(): string

export interface AudioDeviceInfo {
  name: string
  maxInputChannels: number
  maxOutputChannels: number
  defaultSampleRate?: number
}

/** State update sent to JavaScript */
export interface AudioEngineStateUpdate {
  deckAPosition?: number
  deckBPosition?: number
  deckAPlaying: boolean
  deckBPlaying: boolean
  crossfaderPosition: number
  isCrossfading: boolean
  deckAPeak: number
  deckBPeak: number
  deckAPeakHold: number
  deckBPeakHold: number
  masterTempo: number
  deckATrackId?: string
  deckBTrackId?: string
  deckAGain: number
  deckBGain: number
  deckACueEnabled: boolean
  deckBCueEnabled: boolean
  /** EQ cut state for deck A */
  deckAEqCut: EqCutStateJs
  /** EQ cut state for deck B */
  deckBEqCut: EqCutStateJs
  /** Loop state for deck A */
  deckALoop: LoopStateJs
  /** Loop state for deck B */
  deckBLoop: LoopStateJs
  /** Microphone available (input stream created successfully) */
  micAvailable: boolean
  /** Microphone enabled */
  micEnabled: boolean
  /** Microphone peak level */
  micPeak: number
  /** Reason for this state update: "periodic", "seek", "play", "stop", "load", etc. */
  updateReason: string
}

export interface BeatDetectionResultJs {
  /** Detected BPM */
  bpm: number
  /** Beat positions in seconds */
  beats: Array<number>
  /** Confidence score (0-1) */
  confidence: number
}

/** Decode an MP3 file and return PCM data with BPM and structure analysis */
export declare function decodeAudio(mp3Path: string, targetSampleRate: number, targetChannels: number): DecodeResult

/** Decode result containing PCM data and analysis */
export interface DecodeResult {
  /** Interleaved stereo PCM data (Float32) */
  pcm: Buffer
  /** Mono PCM data for waveform display (Float32) */
  mono: Buffer
  /** Detected BPM (if successful) */
  bpm?: number
  /** Track structure analysis (if BPM detected) */
  structure?: TrackStructure
  /** Output sample rate */
  sampleRate: number
  /** Number of channels (always 2 for stereo output) */
  channels: number
}

/**
 * Detect BPM and beat positions from mono audio data.
 * Based on: J. Zapata, M. Davies and E. Gómez, "Multi-feature beat tracker,"
 * IEEE/ACM Transactions on Audio, Speech and Language Processing, 22(4), 816-825, 2014
 */
export declare function detectBeats(audio: Float32Array, sampleRate: number): BeatDetectionResultJs | null

/** Device configuration for configureDevice() */
export interface DeviceConfig {
  /** Device ID (device name, stable across restarts) */
  deviceId?: string
  /** Main output channels [left, right], -1 for disabled */
  mainChannels?: Array<number>
  /** Cue output channels [left, right], -1 for disabled */
  cueChannels?: Array<number>
}

/** EQ cut state for a deck */
export interface EqCutStateJs {
  low: boolean
  mid: boolean
  high: boolean
}

export declare function listAudioDevices(): Array<AudioDeviceInfo>

/** Loop state for a deck */
export interface LoopStateJs {
  /** Whether loop is enabled */
  enabled: boolean
  /** Loop start position (0.0-1.0) */
  start: number
  /** Loop end position (0.0-1.0) */
  end: number
}

/** Track section (intro, main, or outro) */
export interface TrackSection {
  start: number
  end: number
  beats: number
}

/** Track structure analysis result */
export interface TrackStructure {
  bpm: number
  intro: TrackSection
  main: TrackSection
  outro: TrackSection
  hotCues: Array<number>
  beats: Array<number>
}
