/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function addonVersion(): string

/**
 * Attach a native GPU-rendered view to an Electron BrowserWindow.
 *
 * `native_handle` is the Buffer from `BrowserWindow.getNativeWindowHandle()`.
 * On macOS this is a pointer to the NSView (content view).
 * `x`, `y`, `width`, `height` define the frame within the parent window.
 */
export declare function attach(nativeHandle: Buffer, x: number, y: number, width: number, height: number): void

/** Clear deck artwork (show placeholder). */
export declare function clearDeckArtwork(deck: number): void

/** Detach and destroy the native view. */
export declare function detach(): void

export declare function isGpuiEnabled(): boolean

export declare function launchGpuiPreview(): boolean

export interface NativeConsoleState {
  deckA: NativeDeckConsoleState
  deckB: NativeDeckConsoleState
  masterTempo: number
  crossfader: number
}

export interface NativeDeckConsoleState {
  title: string
  timeText: string
  bpmText: string
  bpm: number
  playing: boolean
  loopEnabled: boolean
  loopBeats: number
  loopStart: number
  loopEnd: number
  cueEnabled: boolean
  eqLow: boolean
  eqMid: boolean
  eqHigh: boolean
  gain: number
  peak: number
}

export interface NativeUiAction {
  /** Action type: "play", "stop", "crossfader", "master_tempo", "cue", "eq", "loop", "seek", "load_file" */
  action: string
  /** Deck number (1 or 2), 0 if N/A */
  deck: number
  /** Float value (crossfader pos, tempo, seek pos, loop beats) */
  value: number
  /** String param (eq band: "high"/"mid"/"low") */
  param: string
}

/** Poll pending UI actions from egui interactions. */
export declare function pollActions(): Array<NativeUiAction>

export declare function setConsoleState(state: NativeConsoleState): void

/** Set deck artwork from RGBA pixel data. */
export declare function setDeckArtwork(deck: number, width: number, height: number, rgba: Buffer): void

export declare function setDeckMarkers(deck: number, beats: Array<number>, intro?: number | undefined | null, outro?: number | undefined | null): void

export declare function setDeckProgress(deck: number, positionFrames: number, totalFrames: number, audioSampleRate: number): void

/** Resize / reposition the native view within the parent window. */
export declare function setFrame(x: number, y: number, width: number, height: number): void

/** Set decimated waveform samples for the specified deck. */
export declare function setWaveform(deck: number, samples: Array<number>): void
